###Recuperar todas las pelis
GET http://localhost:5000/movies

###Recuperar una pelicula por id
GET http://localhost:5000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3

###REcuperar pelicula por genero

GET http://localhost:5000/movies?genre=action

### Crear una pelicula con POST
POST http://localhost:5000/movies
Content-Type: application/json

{
    "tittle":"Sexo Potente",
    "year":1999,
    "director":"Lana Wachowski",
    "duration":175,
    "poster":"https://i.ebayimg.com/images/g/4goAAOSwMyBe7hnQ/s-l1200.webp",
    "genre":[
        "Drama"
    ]
}

###Actualizar una pelicula 
PATCH http://localhost:5000/movies/458908bc-0b82-4255-acea-150fa5b4c887
Content-Type: application/json

{
    "year": 2000
}